/*
 * This file was generated by the Gradle("init") task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.10.2/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    id("java")
    application
    id("com.palantir.git-version") version "3.0.0"
    id("org.openjfx.javafxplugin") version "0.1.0"
}


group = "com.gtnewhorizons"
val gitVersion: groovy.lang.Closure<String> by extra
val detectedVersion: String = System.getenv("VERSION") ?: gitVersion()
version = detectedVersion

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
    implementation("org.apache.maven:maven-artifact:3.9.9")
    implementation("com.google.code.gson:gson:2.11.0")
    implementation("org.apache.logging.log4j:log4j-api:2.20.0")
    implementation("org.apache.logging.log4j:log4j-core:2.20.0")
    implementation("commons-io:commons-io:2.18.0")
    implementation("org.jsoup:jsoup:1.18.1")
    implementation("info.picocli:picocli:4.7.6")
    annotationProcessor("info.picocli:picocli-codegen:4.7.6")
    implementation("io.github.mkpaz:atlantafx-base:2.0.1")
    implementation("org.kordamp.ikonli:ikonli-javafx:12.3.1")
    implementation("org.kordamp.ikonli:ikonli-feather-pack:12.3.1")

    compileOnly("org.projectlombok:lombok:1.18.36")
    annotationProcessor("org.projectlombok:lombok:1.18.36")

    testCompileOnly("org.projectlombok:lombok:1.18.36")
    testAnnotationProcessor("org.projectlombok:lombok:1.18.36")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

tasks.withType<Test> {
    systemProperty("file.encoding", "UTF-8")
}

tasks.named<JavaExec>("run") {
    jvmArgs = listOf("-Dfile.encoding=UTF-8", "-Dstdout.encoding=UTF-8", "-Dstderr.encoding=UTF-8")
}

javafx {
    version = "21.0.2"
    modules = listOf("javafx.controls")
}

application {
    mainClass = "GTNHNightlyUpdater.Main"
    tasks {
        // command line args example in a dev env
//        run.get().args = listOf(
//                "-M", "DAILY",
//                "--add",
//                "-m", "/mnt/games/Minecraft/Instances/GTNH_Nightly/.minecraft/",
//                "-s", "CLIENT",
//                "--add",
//                "-m", "/mnt/apps/minenix/appdata/gtnh/",
//                "-s", "server"
//        )
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
    // Skip git-based versioning inside the tests
    environment("VERSION", "1.0.0")
}

tasks {
    withType<Jar> {
        manifest {
            attributes["Main-Class"] = application.mainClass
        }
        duplicatesStrategy = DuplicatesStrategy.EXCLUDE
        // here zip stuff found in runtimeClasspath:
        from(configurations.runtimeClasspath.get().map { if (it.isDirectory) it else zipTree(it) })
    }
}

// `jar` (default task) is the "terminal" build: run with CLI args (`java -jar ...jar -M ...`),
// or double-click/`java -jar` with no args to fall back to the GUI, same as before.
// `guiJar` is byte-for-byte the same fat jar content, just under a name that makes it obvious
// which one to double-click for the GUI (no CLI args needed either way — Main.main launches the
// GUI whenever args is empty).
val guiJar = tasks.register<Jar>("guiJar") {
    group = "build"
    description = "Builds a GUI-labelled copy of the fat jar (double-click friendly; launches the GUI when run with no arguments)."
    archiveBaseName = "gtnh-stable-updater-gui"
    manifest {
        attributes["Main-Class"] = application.mainClass
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from(sourceSets.main.get().output)
    from(configurations.runtimeClasspath.get().map { if (it.isDirectory) it else zipTree(it) })
}

tasks.named("assemble") {
    dependsOn(guiJar)
}

// Best-effort native Windows launcher for the GUI jar, built with the JDK's own `jpackage` tool
// (bundled since JDK 14, so no extra install needed) as an "app-image" — a self-contained folder
// with a real .exe inside and its own bundled JRE, no WiX/installer tooling required. This is
// NOT an installer (no Start Menu entry, no uninstaller) — just a runnable .exe folder.
tasks.register<Exec>("jpackageGuiExe") {
    group = "distribution"
    description = "Packages guiJar into a native Windows .exe app-image via jpackage (no installer, just a runnable folder)."
    dependsOn(guiJar)

    doFirst {
        val javaHome = javaToolchains.launcherFor(java.toolchain).get().executablePath.asFile.parentFile.parentFile
        val jpackageBin = javaHome.resolve("bin").resolve(
            if (org.gradle.internal.os.OperatingSystem.current().isWindows) "jpackage.exe" else "jpackage"
        )
        val destDir = layout.buildDirectory.dir("jpackage").get().asFile
        delete(destDir)
        destDir.mkdirs()

        val safeVersion = version.toString().takeWhile { it.isDigit() || it == '.' }
            .trim('.')
            .ifBlank { "1.0.0" }
            .let { v -> if (v.count { c -> c == '.' } < 2) "$v.0.0".split(".").take(3).joinToString(".") else v }

        commandLine(
            jpackageBin.absolutePath,
            "--type", "app-image",
            "--name", "GTNH Stable Updater",
            "--input", guiJar.get().destinationDirectory.get().asFile.absolutePath,
            "--main-jar", guiJar.get().archiveFileName.get(),
            "--main-class", application.mainClass.get(),
            "--dest", destDir.absolutePath,
            "--vendor", "Folbrich",
            "--app-version", safeVersion
        )
    }
}
